// ADR-208：自帶日光／夜間底圖；所有資源維持 OpenFreeMap 同源。
import { palettes } from "../theme/palettes.js";

const TILE_ORIGIN = "https://tiles.openfreemap.org";


export function createBasemapStyle(mode = "light") {
  const palette = (palettes[mode] ?? palettes.light).map;
  return {
    version: 8,
    name: `YouBike ${mode}`,
    glyphs: `${TILE_ORIGIN}/fonts/{fontstack}/{range}.pbf`,
    sprite: `${TILE_ORIGIN}/sprites/ofm_f384/ofm`,
    sources: {
      openmaptiles: {
        type: "vector",
        url: `${TILE_ORIGIN}/planet`,
      },
    },
    layers: [
      {
        id: "background",
        type: "background",
        paint: { "background-color": palette.background },
      },
      {
        id: "landcover-wood",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "landcover",
        filter: ["==", ["get", "class"], "wood"],
        paint: { "fill-color": palette.wood, "fill-opacity": 0.35 },
      },
      {
        id: "park",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "park",
        paint: { "fill-color": palette.park, "fill-opacity": 0.4 },
      },
      {
        id: "water",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "water",
        filter: ["!=", ["get", "brunnel"], "tunnel"],
        paint: { "fill-color": palette.water },
      },
      {
        id: "waterway",
        type: "line",
        source: "openmaptiles",
        "source-layer": "waterway",
        paint: {
          "line-color": palette.waterway,
          "line-width": [
            "interpolate",
            ["exponential", 1.3],
            ["zoom"],
            11,
            0.5,
            20,
            5,
          ],
        },
      },
      {
        id: "building",
        type: "fill",
        source: "openmaptiles",
        "source-layer": "building",
        minzoom: 13,
        paint: {
          "fill-color": palette.building,
          "fill-outline-color": palette.buildingOutline,
          "fill-opacity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            13,
            0,
            14.5,
            0.7,
          ],
        },
      },
      {
        id: "road-casing",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        filter: [
          "match",
          ["get", "class"],
          ["motorway", "trunk", "primary", "secondary", "tertiary"],
          true,
          false,
        ],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": palette.roadCasing,
          "line-width": [
            "interpolate",
            ["exponential", 1.2],
            ["zoom"],
            6,
            0.6,
            14,
            6,
            20,
            26,
          ],
        },
      },
      {
        id: "road-minor",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        minzoom: 12,
        filter: [
          "match",
          ["get", "class"],
          ["minor", "service", "track"],
          true,
          false,
        ],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": palette.roadMinor,
          "line-width": [
            "interpolate",
            ["exponential", 1.2],
            ["zoom"],
            12,
            0.4,
            16,
            2.5,
            20,
            14,
          ],
        },
      },
      {
        id: "road-secondary-tertiary",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        filter: [
          "match",
          ["get", "class"],
          ["secondary", "tertiary"],
          true,
          false,
        ],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": palette.roadMajor,
          "line-width": [
            "interpolate",
            ["exponential", 1.2],
            ["zoom"],
            8,
            0.8,
            16,
            5,
            20,
            16,
          ],
        },
      },
      {
        id: "road-trunk-primary",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        filter: [
          "match",
          ["get", "class"],
          ["primary", "trunk"],
          true,
          false,
        ],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": palette.roadMajor,
          "line-width": [
            "interpolate",
            ["exponential", 1.2],
            ["zoom"],
            6,
            1,
            14,
            6,
            20,
            22,
          ],
        },
      },
      {
        id: "road-motorway",
        type: "line",
        source: "openmaptiles",
        "source-layer": "transportation",
        filter: ["==", ["get", "class"], "motorway"],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": palette.motorway,
          "line-width": [
            "interpolate",
            ["exponential", 1.2],
            ["zoom"],
            5,
            1,
            14,
            7,
            20,
            24,
          ],
        },
      },
      {
        id: "boundary",
        type: "line",
        source: "openmaptiles",
        "source-layer": "boundary",
        filter: ["<=", ["get", "admin_level"], 4],
        paint: {
          "line-color": palette.boundary,
          "line-dasharray": [2, 2],
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            4,
            0.6,
            12,
            2,
          ],
        },
      },
      {
        id: "place-label",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "place",
        filter: [
          "match",
          ["get", "class"],
          ["city", "town", "village"],
          true,
          false,
        ],
        layout: {
          "text-field": [
            "case",
            ["has", "name:nonlatin"],
            [
              "concat",
              ["get", "name:latin"],
              "\n",
              ["get", "name:nonlatin"],
            ],
            ["coalesce", ["get", "name_en"], ["get", "name"]],
          ],
          "text-font": ["Noto Sans Regular"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            6,
            11,
            12,
            15,
          ],
        },
        paint: {
          "text-color": palette.label,
          "text-halo-color": palette.labelHalo,
          "text-halo-width": 1.2,
        },
      },
      {
        id: "water-label",
        type: "symbol",
        source: "openmaptiles",
        "source-layer": "water_name",
        minzoom: 10,
        layout: {
          "text-field": [
            "coalesce",
            ["get", "name_en"],
            ["get", "name"],
          ],
          "text-font": ["Noto Sans Italic"],
          "text-size": 12,
          "text-max-width": 5,
        },
        paint: {
          "text-color": palette.waterLabel,
          "text-halo-color": palette.labelHalo,
          "text-halo-width": 1,
        },
      },
    ],
  };
}

export function createDarkBasemapStyle() { return createBasemapStyle("dark"); }
